### ISSUE TITLE
Test suite fails with old Mojolicious (< 6.0)

### ISSUE THREAD

**Issue by eserte** [sshaw/Mojolicious-Plugin-MoreUtilHelpers#2]
See http://analysis.cpantesters.org/reports_by_field?distv=Mojolicious-Plugin-MoreUtilHelpers-0.04;field=mod%3AMojolicious for a report analysis. It seems that there are only PASSes for Mojolicious 6, and FAILs for Mojolicious 5 and older.

**Comment by sshaw** [comment]
Yes, forgot to update the min requirement, which was fixed in 86003eccf41e60f029de249e1a6ea9b627c40ad0
